# Generated by Django 5.0.1 on 2024-02-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbUsersAndOrdersApp', '0003_alter_order_total_price_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
    ]
