# Generated by Django 5.0.1 on 2024-02-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbUsersAndOrdersApp', '0004_rename_products_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
