# Generated by Django 5.0.1 on 2024-02-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbUsersAndOrdersApp', '0006_alter_order_date_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
