# Generated by Django 5.0.1 on 2024-02-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbUsersAndOrdersApp', '0007_rename_product_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
