# Generated by Django 5.0.1 on 2024-02-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbUsersAndOrdersApp', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
